---
# See https://github.com/nginxinc/ansible-role-nginx/issues/507
- name: Install gpg-agent (NGINX role prerequisite)
  ansible.builtin.package:
    name: gpg-agent
    state: present

- name: Install nginx
  ansible.builtin.include_role:
    name: nginxinc.nginx
  when: sonarr__use_nginx

- name: Create NGINX enabled sites directory
  ansible.builtin.file:
    path: /etc/nginx/enabled
    state: directory
    mode: "0644"
    owner: root
    group: root
  notify:
    - Restart NGINX

- name: Remove default site
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify:
    - Restart NGINX

- name: Configure NGINX for Sonarr
  ansible.builtin.copy:
    src: "{{ item.file }}"
    dest: "{{ item.dest }}"
    mode: "0644"
    owner: root
    group: root
  with_items:
    - file: nginx-sonarr.conf
      dest: /etc/nginx/enabled/sonarr.conf
    - file: nginx.conf
      dest: /etc/nginx/nginx.conf
  notify:
    - Restart NGINX
